language: java
jdk:
  - oraclejdk8
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
install: "mvn install --settings target/travis/settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
script: "mvn test --settings target/travis/settings.xml -Dmaven.javadoc.skip=true -B"
after_success: "mvn deploy --settings target/travis/settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B"
branches:
  except:
    - travis
